version: '3.8'
services:
  front-end:
    image: bankjirayuth/devtool-compose-front:1.0.0
    build: ./front-end
    ports:
      - "3035:80"
      
  back-end:
    image: bankjirayuth/devtool-compose-back:1.0.0
    build: ./back-test/app
    ports:
      - "4035:3000"